[project]
name = "freegames"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.21.0",
    "audioop-lts>=0.2.2",
    "httpx>=0.28.1",
    "psutil>=7.1.3",
    "py-cord[voice]>=2.6.1",
    "python-dotenv>=1.2.1",
]
